account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account import views
from django.conf import settings
from django.conf.urls.static import static
from post.views import *

urlpatterns = [
      # path('login/',auth_views.LoginView.as_view(),name='login'),
      path('login/',views.user_login,name='login'),
      path('logout/',views.logout_function,name='logout'),
      path('register/',views.register,name='register'),
      path('',views.post_list,name='dashboard'),
      path('profile/',views.edit,name='edit'),
      path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
      path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'post'
urlpatterns = [
		path('',views.post_list,name='post_list_view'),
		path('like/',views.like_post,name='like_post'),
		path('post/<int:id>/',views.post_detail,name='post_detail'),
		path('my_post/',views.my_post,name='my_post'),
		path('edit_post/<int:id>/',views.post_edit,name='post_edit'),
		# path('delete/',views.del_view,name='del_view'),
		path('delete/<int:id>',views.post_delete,name='del_post'),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('posts/',include('post.urls',namespace='post')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,
                                related_name='profile')
    birth_date = models.DateField(blank=True,null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d',blank=True)

    def __str__(self):
        return f"Profile {self.user.username}"

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import Profile

class LoginForm(forms.Form):
	username = forms.CharField(label="Username / Email")
	password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password',
                               widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email')

    #check password and password2 matches
    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Both Password Doesn\'t match')
        return cd['password2']
    #check email exists or not
    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError('Sorry Email already exists')
        return email

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','first_name','last_name')

class ProfileEditForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.TextInput(attrs={'placeholder': 'YYYY - MM - DD'}))
    class Meta:
        model = Profile
        fields = ('birth_date','photo')

account/views.py
from django.shortcuts import render,redirect
from .forms import UserRegistrationForm,LoginForm,UserEditForm,ProfileEditForm
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,authenticate
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import logout,login,authenticate
from .decorators import unaunth_user
from post.views import *
from django.urls import reverse
# Create your views here.

@unaunth_user
def user_login(request):
  if request.method == "POST":
      form = LoginForm(request.POST)
      if form.is_valid():
          cd = form.cleaned_data
          user = authenticate(request, username=cd['username'],
                                       password=cd['password'])
          if user is not None:
              if user.is_active:
                  login(request, user)
                  return redirect('post:post_list_view')
              else:
                  return HttpResponse("Account is Disabled")
          else:
              messages.warning(request,"Invalid Username and Password")

  else:
      form = LoginForm()
  return render(request,'registration/login.html',{'form':form})

@unaunth_user
def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            username = user_form.cleaned_data.get('username')
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            messages.success(request,f'Account created for {username}!')
            return redirect('login')
    else:
        user_form = UserRegistrationForm()
    return render(request,'account/register.html',{'user_form':user_form})

@login_required
def dashboard(request):
    return render(request,'account/dashboard.html')

def logout_function(request):
    logout(request)
    messages.success(request,'Successfully Logged Out.')
    return redirect('login')

def edit(request):
    if request.method == "POST":
        # profile = Profile.objects.create(user=request.user)
        data = Profile.objects.filter(user=request.user)
        user_form = UserEditForm(instance=request.user,data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,"Profile Updated Success.")
        else:
            messages.error(request,"Error On Updating")
    else:
        # profile = Profile.objects.create(user=request.user)
        data = Profile.objects.filter(user=request.user)
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,'account/edit.html',{'user_form':user_form,'profile_form':profile_form,'data':data})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'css/w3/css.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/w3/font-awesome.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/w3/w3-theme-blue-grey.css' %}">
    <link rel="stylesheet" href="{% static 'css/w3/w3.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>

      <nav class="navbar bg-primary navbar-dark navbar-expand-sm mb-2">
         <div class="container">
           <a class="navbar-brand ml-2" href="#">Brand</a>
      {% if request.user.is_authenticated %}
           <button type="button" class="navbar-toggler pull-right" data-toggle="collapse"
           data-target="#go">
           <span class="navbar-toggler-icon"></span>
           </button>
         <div class="collapse navbar-collapse justify-content-end mt-auto justify-text-end" id="go">
           <div class="navbar-nav justify-content-end">
               <a class="nav-item nav-link mr-2" href="{% url 'post:post_list_view' %}">Home</a>
               <a class="nav-item nav-link mr-2" href="{% url 'post:my_post' %}">My Post</a>
               <div class="dropdown">
                  <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Privacy
                        </a>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <a class="dropdown-item" href="{% url 'edit' %}">Profile details</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    <a class="dropdown-item" href="#">Posts Liked</a>
                  </div>
              </div>
               <a class="nav-item nav-link mr-2" href="{% url 'logout' %}">Logout</a>
       {% endif %}
           </div>
         </div>
       </div>

      </nav>

      {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                      {{ message }}
                  </div>
              {% endfor %}
             {% endif  %}
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/js.cookie.min.js' %}"></script>
      <script type="text/javascript">
        $(document).ready(function(event){
          $(document).on('click', '#like', function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url 'post:like_post' %}',
              data: {'post_id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                $('#like-section').html(response['form'])
                console.log($('#like-section').html(response['form']));
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });
        });
      </script>
  </body>
</html>