post/urls.py
from django.urls import path
from post import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'post'
urlpatterns = [
		path('',views.post_list,name='post_list_view'),
		path('like/',views.like_post,name='like_post'),
		path('post/<int:id>/',views.post_detail,name='post_detail'),
		path('my_post/',views.my_post,name='my_post'),
		path('edit_post/<int:id>/',views.post_edit,name='post_edit'),
		# path('delete/',views.del_view,name='del_view'),
		path('delete/<int:id>',views.post_delete,name='del_post'),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('posts/',include('post.urls',namespace='post')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='post')
	title = models.CharField(max_length=100)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='storage/',blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	likes = models.ManyToManyField(User,related_name='likes',
										blank=True)


	def __str__(self):
		return self.title

	def date_posted(self):
		return self.created.strftime('%b %d %Y')

	def total_likes(self):
		return self.likes.count()

	def get_absolute_url(self):
		return reverse('post:post_detail',args=[self.id])


class Comment(models.Model):
	user = models.ForeignKey(Post,on_delete=models.CASCADE,
												related_name='comment')
	texts = models.TextField()
	active = models.BooleanField(default=True,null=True)
	author = models.CharField(max_length=100,null=True)
	created = models.DateTimeField(auto_now_add=True)

	def date_commented(self):
		return self.created.strftime('%b %d')

post/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
	title = forms.CharField(required=False,widget=forms.TextInput(attrs={'placeholder': 'Write a Post'}))
	image = forms.ImageField(required=False)
	class Meta:
		model = Post
		fields = ('title','image')

class PostEditForm(forms.ModelForm):
	title = forms.CharField()
	image = forms.ImageField(required=False)
	class Meta:
		model = Post
		fields = ('title','image')

class CommentForm(forms.ModelForm):
	texts = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Write a comment'}))

	class Meta:
		model = Comment
		fields = ('texts',)

post/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Post
from .forms import PostForm,PostEditForm,CommentForm
from django.http import JsonResponse                
from common.decorators import ajax_required
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string 
# Create your views here.

@login_required
def post_list(request):
	obj_list = Post.objects.all().order_by('-created')
	paginator = Paginator(obj_list, 5)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	# form posting
	form = PostForm(request.POST or None, request.FILES or None)
	if request.method == "POST":
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = request.user;
			obj.save()
			messages.success(request,"Post has been added Succesfully.")
			return redirect('post:post_list_view')
		else:
			form = PostForm()
	return render(request,'post/post_view.html',
							{'posts' : posts,
							 'page' : page,
							 'form': form})
@login_required
def post_detail(request, id):
	post = get_object_or_404(Post, id=id)

	#like section
	is_liked = False
	if post.likes.filter(id=request.user.id).exists():
		is_liked = True
	total_likes = post.total_likes()

	# comment section
	comments = post.comment.filter(active=True)
	new_comment = None
	if request.method == 'POST':
		form = CommentForm(data=request.POST)
		if form.is_valid():
			data = form.cleaned_data['texts']
			post.comment.create(texts=data,author=request.user)
			# new_comment.save()
	else:
		form = CommentForm()

	return render(request,'post/post_full.html',{'post':post,
												 'is_liked':is_liked,
												 'total_likes':total_likes,
												 'form':form,
												 'comments':comments})
@login_required
def like_post(request):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	is_liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		is_liked = False 
	else:
		post.likes.add(request.user)
		is_liked = True
	context = {'post':post,
			   'is_liked':is_liked,
			   'total_likes':post.total_likes()
    }
	# return HttpResponseRedirect(post.get_absolute_url())
	if request.is_ajax():
		html = render_to_string('post/like_section.html',context,request=request)
		return JsonResponse({'form':html})

def my_post(request):
	posts = Post.objects.filter(user=request.user).order_by('-created')
	return render(request,'post/my_post.html',{'posts':posts})

def post_edit(request,id):
	post = Post.objects.get(id=id)
	if request.method == "POST":
		form = PostEditForm(request.POST, instance=post,files=request.FILES)
		if form.is_valid():
			form.save()
			return redirect('post:my_post')
		else:
			form = PostEditForm(instance=post)
	else:
		form = PostEditForm(instance=post)
	return render(request,'post/edit_form.html',
				 {'form' : form, 'post':post})

@login_required
def post_delete(request,id):
	post = Post.objects.get(id=id)
	post.delete()
	messages.success(request,"Post has been deleted Succesfully")
	return redirect('post:my_post')

post/templates/post/edit_form.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data">
	{{ form.as_p }}
	{% csrf_token %}
	<button type="submit" class="registerbtn mb-4">Save</button>
</form>
<!-- Button trigger modal -->
			<a type="button" class="text-danger" data-toggle="modal" data-target="#exampleModalCenter" style="display: inline-block;">
			  Delete this Post
			</a>

			<!-- Modal -->
			<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			  <div class="modal-dialog modal-dialog-centered" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="exampleModalLongTitle">Delete</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			        Do you want to delete this post?
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			        <a type="button" class="btn btn-danger" href="{% url 'post:del_post' post.id %}">Delete</a>
			      </div>
			    </div>
			  </div>
			</div>

{% endblock %}

<script>
	$document.ready(function(){
		$('#delete').click(function(){
			$('#delModal').modal('show');
		});
	});
</script>

post/templates/post/like_section.html
<div style="float:right;">
      <form action="{% url 'post:like_post' %}" method="post" class="mb-5">
        {% csrf_token %}
        <p style="display:inline;">{{ total_likes }} Likes<p>
        {% if is_liked %}
          <a type="submit" id="like" name="post_id" value="{{ post.id }}"><i class="material-icons like">favorite</i></a>
        {% else %}
          <a type="submit" id="like" name="post_id" value="{{ post.id }}"><i class="material-icons unlike">favorite</i></a>
        {% endif %}
      </form>
  </div>

post/templates/post/liked_post.html
{% extends 'base.html' %}

{% block title %}Liked Post{% endblock %}

{% block content %}

{% for ele in posts %}

{{ ele.title }}

{% endfor %}
{% endblock %}

post/templates/post/my_post.html
{% extends 'base.html' %}

{% block title %}My Post{% endblock %}

{% load static %}
{% block content %}
{% if posts %}
{% for post in posts %}
	<div class="w3-container w3-card w3-white w3-round w3-margin"><br>
		<div class="first">
		<img src="{% if post.user.profile.photo %} {{post.user.profile.photo.url}} 
		        {% else %}{% static 'img/user.png' %}{% endif %}" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px;max-height: 60px;">
        <div style="float: right;">
	        <a type="button" class="btn btn-default btn-sm" href="{% url 'post:post_edit' post.id %}">
	          <span class="glyphicon glyphicon-pencil"></span> Edit 
	        </a>
        </div>
		</div>
	        <h4>{{ post.user|title }}</h4><br>
	        <hr class="w3-clear">
	        <!-- <a href="{% url 'post:post_detail' post.id %}" style="color: black;"> -->
        	<a href="{{ post.get_absolute_url }}" style="color: black;">
	        <p>{{ post.title }}</p>
	        {% if post.image %}
	        <div style="max-width:100%;height:auto;object-fit: cover;" class="img-fluid">
	        	<img src="{{ post.image.url }}" class="img-fluid" style="max-width:100%;height:auto;object-fit: cover;">
	        </div>
	        <p>{{ post.description }}</p>
	    	</a>
	    	{% endif %}
	    	{% with total_likes=post.likes.count users_like=post.likes.all %}
		    <div class="image-info">
		      <div>
		        <span class="count">
		          <span class="total">Comments</span>
		        </span>
	    	  </div>
		    </div>   
    	{% endwith %} 
</div>
	{% endfor %}
 {% else %}
 	<center>No posts Yet.</center>
 {% endif %}
{% endblock %}

post/templates/post/pagination.html
<div class="pagination justify-content-center mb-5">
	<span>
		{% if page.has_previous %}
		    <a href="?page={{ page.previous_page_number }}" class="page-slide">< Prev</a>
	    {% endif %}
	    <!-- <span>
	    	Page {{ page.number }} of {{ page.paginator.num_pages }}
	    </span> -->
	    {% if page.has_next %}
		    <a href="?page={{ page.next_page_number }}" class="page-slide">Next ></a>
	    {% endif %}
	</span>
</div>

post/templates/post/post_full.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="container">
	<div class="first">
		<img src="{% if post.user.profile.photo %} {{post.user.profile.photo.url}} 
		        {% else %}{% static 'img/user.png' %}{% endif %}" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px;max-height: 60px;">
		        <span class="w3-right w3-opacity" style="display: inline;">{{ post.date_posted }}</span>
        <br>
    </div>
    <div class="second">
	    <h3 style="display: inline-grid;">{{ post.user|title }}</h3>
	    <br>
		<p>{{ post.description }}</p>
		{% if post.image %}
		<img src="{{ post.image.url }}" class="img-fluid img-fit mb-2" style="border-radius: 5px;">
		{% endif %}
		<p>{{ post.title }}</p>	
	</div>

	<!-- like section -->
	<div id="like-section">
		{% include 'post/like_section.html' %}
	</div>

	<!-- comment section -->
	<div id="comment-section">
		{% for com in comments %}
		<p><strong>{{ com.author|capfirst }}</strong>&nbsp;
			<span class="text-muted display-6" style="float: center">{{ com.date_commented }}</span></p>
		<h6><i>{{ com.texts }}</i></h6>
		{% empty %}
		  <p>No Comments yet</p>
	  	{% endfor %}
	    <hr>
	    <h4>Comment</h4>
	    <form method="POST">
	    	{{ form.as_p }}
	    	{% csrf_token %}
	    	<input type="submit" value="Add Comment" style="inline-block">
	    </form>
    </div>
</div>
{% endblock %}

post/templates/post/post_view.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Brand Home{% endblock %}

{% block content %}
<div class="container-fluid mr-0">
	<form name="post-form" method="post" enctype="multipart/form-data">
		<input name="title" class="form-control" type="text" placeholder="Write a Post">
		<input name="image" type="file">
		<!-- {{ form.as_p }} -->
		{% csrf_token %}
		<input type="submit" class="postbtn" value="Post">
	</form>
</div>

{% for post in posts %}
	<div class="container-auto-md"><br>
		{% load thumbnail %}
	        <img src="{% if post.user.profile.photo %} {{post.user.profile.photo.url}} 
	        {% else %}{% static 'img/user.png' %}{% endif %}" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px;
	        max-height: 60px;">
	        <span class="w3-right w3-opacity">{{ post.created|timesince }}</span>
	        <h4>{{ post.user|title }}</h4><br>
	        <hr class="w3-clear">
	        <!-- <a href="{% url 'post:post_detail' post.id %}" style="color: black;"> -->
        	<a href="{{ post.get_absolute_url }}" style="color: black;">
	        <p>{{ post.title }}</p>
	        {% if post.image %}
	        <div style="max-width:100%;height:auto;object-fit: cover;" class="img-fluid">
	        	<!-- <img src="{{ post.image.url }}" class="img-fluid" style="max-width:100%;height:auto;object-fit: cover; -->
	        	<!-- border-radius: 5px;"> -->
	        	<img src="{{ post.image.url }}" class="img-fluid" style="width: 100%;max-width: 1000px;margin: auto;
	        	border-radius: 5px;">
	        </div>
	        <p>{{ post.description }}</p>
	    	</a>
	    	{% endif %}
	    	{% with total_likes=post.likes.count users_like=post.likes.all %}
		    <div class="image-info">
		      <div>
		        <span class="count">
		          <span class="total">Comments</span>
		        </span>
	    	  </div>
		    </div>   
    	{% endwith %} 
</div>

	{% endfor %}
	{% include 'post/pagination.html' with page=posts %}

{% endblock %}